/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppChallengesRouteImport } from './routes/_app.challenges'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppMastersRouteImport } from './routes/_app.masters'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app.accounts.$accountId'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminChallengesRouteImport } from './routes/_app.admin.challenges'
import { Route as AppChallengesIndexRouteImport } from './routes/_app.challenges.index'
import { Route as AppChallengesHistoryRouteImport } from './routes/_app.challenges.history'
import { Route as AppInsightAccountIdRouteImport } from './routes/_app.insight.$accountId'
import { Route as AppPaymentsReferenceRouteImport } from './routes/_app.payments.$reference'
import { Route as AppAdminMastersIndexRouteImport } from './routes/_app.admin.masters.index'
import { Route as AppAdminMastersAccountIdRouteImport } from './routes/_app.admin.masters.$accountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminChallengesRoute = AppAdminChallengesRouteImport.update({
  id: '/admin/challenges',
  path: '/admin/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesIndexRoute = AppChallengesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChallengesRoute,
} as any)
const AppChallengesHistoryRoute = AppChallengesHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppChallengesRoute,
} as any)
const AppInsightAccountIdRoute = AppInsightAccountIdRouteImport.update({
  id: '/insight/$accountId',
  path: '/insight/$accountId',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsReferenceRoute = AppPaymentsReferenceRouteImport.update({
  id: '/payments/$reference',
  path: '/payments/$reference',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMastersIndexRoute = AppAdminMastersIndexRouteImport.update({
  id: '/admin/masters/',
  path: '/admin/masters/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMastersAccountIdRoute =
  AppAdminMastersAccountIdRouteImport.update({
    id: '/admin/masters/$accountId',
    path: '/admin/masters/$accountId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof AppChallengesRouteWithChildren
  '/checkout': typeof AppCheckoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/masters': typeof AppMastersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pricing': typeof AppPricingRoute
  '/settings': typeof AppSettingsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/admin/challenges': typeof AppAdminChallengesRoute
  '/challenges/history': typeof AppChallengesHistoryRoute
  '/insight/$accountId': typeof AppInsightAccountIdRoute
  '/payments/$reference': typeof AppPaymentsReferenceRoute
  '/admin/': typeof AppAdminIndexRoute
  '/challenges/': typeof AppChallengesIndexRoute
  '/admin/masters/$accountId': typeof AppAdminMastersAccountIdRoute
  '/admin/masters/': typeof AppAdminMastersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof AppCheckoutRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/masters': typeof AppMastersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pricing': typeof AppPricingRoute
  '/settings': typeof AppSettingsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/admin/challenges': typeof AppAdminChallengesRoute
  '/challenges/history': typeof AppChallengesHistoryRoute
  '/insight/$accountId': typeof AppInsightAccountIdRoute
  '/payments/$reference': typeof AppPaymentsReferenceRoute
  '/admin': typeof AppAdminIndexRoute
  '/challenges': typeof AppChallengesIndexRoute
  '/admin/masters/$accountId': typeof AppAdminMastersAccountIdRoute
  '/admin/masters': typeof AppAdminMastersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/challenges': typeof AppChallengesRouteWithChildren
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/masters': typeof AppMastersRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/admin/challenges': typeof AppAdminChallengesRoute
  '/_app/challenges/history': typeof AppChallengesHistoryRoute
  '/_app/insight/$accountId': typeof AppInsightAccountIdRoute
  '/_app/payments/$reference': typeof AppPaymentsReferenceRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/challenges/': typeof AppChallengesIndexRoute
  '/_app/admin/masters/$accountId': typeof AppAdminMastersAccountIdRoute
  '/_app/admin/masters/': typeof AppAdminMastersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challenges'
    | '/checkout'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/masters'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/accounts/$accountId'
    | '/admin/challenges'
    | '/challenges/history'
    | '/insight/$accountId'
    | '/payments/$reference'
    | '/admin/'
    | '/challenges/'
    | '/admin/masters/$accountId'
    | '/admin/masters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/masters'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/accounts/$accountId'
    | '/admin/challenges'
    | '/challenges/history'
    | '/insight/$accountId'
    | '/payments/$reference'
    | '/admin'
    | '/challenges'
    | '/admin/masters/$accountId'
    | '/admin/masters'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/challenges'
    | '/_app/checkout'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/leaderboard'
    | '/_app/masters'
    | '/_app/onboarding'
    | '/_app/pricing'
    | '/_app/settings'
    | '/_app/accounts/$accountId'
    | '/_app/admin/challenges'
    | '/_app/challenges/history'
    | '/_app/insight/$accountId'
    | '/_app/payments/$reference'
    | '/_app/admin/'
    | '/_app/challenges/'
    | '/_app/admin/masters/$accountId'
    | '/_app/admin/masters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/challenges': {
      id: '/_app/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/challenges': {
      id: '/_app/admin/challenges'
      path: '/admin/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AppAdminChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges/': {
      id: '/_app/challenges/'
      path: '/'
      fullPath: '/challenges/'
      preLoaderRoute: typeof AppChallengesIndexRouteImport
      parentRoute: typeof AppChallengesRoute
    }
    '/_app/challenges/history': {
      id: '/_app/challenges/history'
      path: '/history'
      fullPath: '/challenges/history'
      preLoaderRoute: typeof AppChallengesHistoryRouteImport
      parentRoute: typeof AppChallengesRoute
    }
    '/_app/insight/$accountId': {
      id: '/_app/insight/$accountId'
      path: '/insight/$accountId'
      fullPath: '/insight/$accountId'
      preLoaderRoute: typeof AppInsightAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$reference': {
      id: '/_app/payments/$reference'
      path: '/payments/$reference'
      fullPath: '/payments/$reference'
      preLoaderRoute: typeof AppPaymentsReferenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/masters/': {
      id: '/_app/admin/masters/'
      path: '/admin/masters'
      fullPath: '/admin/masters/'
      preLoaderRoute: typeof AppAdminMastersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/masters/$accountId': {
      id: '/_app/admin/masters/$accountId'
      path: '/admin/masters/$accountId'
      fullPath: '/admin/masters/$accountId'
      preLoaderRoute: typeof AppAdminMastersAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChallengesRouteChildren {
  AppChallengesHistoryRoute: typeof AppChallengesHistoryRoute
  AppChallengesIndexRoute: typeof AppChallengesIndexRoute
}

const AppChallengesRouteChildren: AppChallengesRouteChildren = {
  AppChallengesHistoryRoute: AppChallengesHistoryRoute,
  AppChallengesIndexRoute: AppChallengesIndexRoute,
}

const AppChallengesRouteWithChildren = AppChallengesRoute._addFileChildren(
  AppChallengesRouteChildren,
)

interface AppRouteChildren {
  AppChallengesRoute: typeof AppChallengesRouteWithChildren
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMastersRoute: typeof AppMastersRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAdminChallengesRoute: typeof AppAdminChallengesRoute
  AppInsightAccountIdRoute: typeof AppInsightAccountIdRoute
  AppPaymentsReferenceRoute: typeof AppPaymentsReferenceRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminMastersAccountIdRoute: typeof AppAdminMastersAccountIdRoute
  AppAdminMastersIndexRoute: typeof AppAdminMastersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChallengesRoute: AppChallengesRouteWithChildren,
  AppCheckoutRoute: AppCheckoutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMastersRoute: AppMastersRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPricingRoute: AppPricingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAdminChallengesRoute: AppAdminChallengesRoute,
  AppInsightAccountIdRoute: AppInsightAccountIdRoute,
  AppPaymentsReferenceRoute: AppPaymentsReferenceRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminMastersAccountIdRoute: AppAdminMastersAccountIdRoute,
  AppAdminMastersIndexRoute: AppAdminMastersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}